export default {
    PACKAGES_STORAGE_PATH: "/data/packages.json",
    LANGUAGES_STORAGE_PATH: "/data/languages.json",
    SETTINGS_STORAGE_PATH: "/data/settings.json",
    DEFAULT_NETWORK_NAME: "epi",
    XSL_PATH: "/code/assets/xml/leaflet.xsl",
    SN_FAIL_ICON: "assets/icons/serial_number/sn_fail_red_x.svg",
    SN_FAIL_MESSAGE: "Failed",
    SN_RECALLED_MESSAGE: "Recalled",
    SN_DECOMMISSIONED_MESSAGE: "Decommissioned",
    SN_OK_ICON: "assets/icons/serial_number/sn_ok.png",
    SN_GRAY_ICON: "assets/icons/serial_number/SN_gray_icon.svg",
    SN_OK_MESSAGE: "Verified",
    SN_UNABLE_TO_VERIFY_MESSAGE: "Unable to verify",
    PRODUCT_STATUS_FAIL_ICON: "assets/icons/product_status/ps_fail_red_x.svg",
    PRODUCT_STATUS_FAIL_MESSAGE: "Invalid expiry date",
    PRODUCT_EXPIRED_MESSAGE: "Product expired",
    PRODUCT_STATUS_OK_ICON: "assets/icons/product_status/ps_ok.png",
    PRODUCT_STATUS_GRAY_ICON: "assets/icons/product_status/ps_gray_icon.svg",
    PRODUCT_STATUS_OK_MESSAGE: "Verified",
    PRODUCT_STATUS_UNABLE_TO_VALIDATE_MESSAGE: "Unable to validate",
    PACK_VERIFICATION_GRAY_ICON: "assets/icons/pack_verification/svg/PV_gray_icon.svg",
    PACK_VERIFICATION_ICON: "assets/icons/pack_verification/svg/PV_icon.svg",
    PACK_VERIFICATION_UNABLE_TO_VERIFY_MESSAGE: "Unable to verify",
}
