apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: epi
  name: epi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: epi
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: epi
    spec:
      containers:
      - image: pharmaledger/epi:latest
        imagePullPolicy: ""
        name: epi
        ports:
          - containerPort: 8080
        resources: {}
        volumeMounts:
          - name: epi-defaults-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/apihub.json
            subPath: apihub.json
          - name: epi-domains
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/default.json
            subPath: default.json
          - name: epi-domains
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/epipharma.json
            subPath: epipharma.json
          - name: epi-domains
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/epi.json
            subPath: epi.json
          - name: epi-domains
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/epiqa.json
            subPath: epiqa.json
          - name: epi-domains
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/predefined.json
            subPath: predefined.json
          - name: epi-domains
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/vault.jnj.json
            subPath: vault.jnj.json
          - name: epi-domains
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/vault.json
            subPath: vault.json
          - name: epi-domains
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/vault.msd.json
            subPath: vault.msd.json
          - name: epi-domains
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/vault.nvs.json
            subPath: vault.nvs.json
          - name: epi-defaults-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/bdns.hosts
            subPath: bdns.hosts
          - name: epi-defaults-volume
            mountPath: /ePI-workspace/env.json
            subPath: env.json
          - name: epi-defaults-volume
            mountPath: /ePI-workspace/apihub-root/seedsBackup
            subPath: seedsBackup
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: epi-defaults-volume
          configMap:
            name: epi-defaults
        - name: epi-domains
          configMap:
            name: epi-default-domains
status: {}
